### ISSUE TITLE
Plans to support newer android versions

### ISSUE THREAD

**Issue by timehlers** [nelenkov/keystore-decryptor#8]
Hi,

I just tested your tool and it indeed worked for older android keys, but current android versions (like 12) seem to have changed indeed and fail with:

tehlers@acer:~/keystore-decryptor> java -jar ksdecryptor-all.jar user_0.opNord/.masterkey user_0.opNord/.10136_chr_USRPKEY_FingerprintKey 1234
Read '.masterkey'
Exception in thread "main" java.lang.RuntimeException: javax.crypto.IllegalBlockSizeException: data not block size aligned
        at org.nick.ksdecryptor.KeystoreBlob.parseMasterKey(KeystoreBlob.java:109)
        at org.nick.ksdecryptor.Main.main(Main.java:45)
Caused by: javax.crypto.IllegalBlockSizeException: data not block size aligned
        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
        at org.nick.ksdecryptor.KeystoreBlob.decrypt(KeystoreBlob.java:172)
        at org.nick.ksdecryptor.KeystoreBlob.parseMasterKey(KeystoreBlob.java:84)
        ... 1 more

Which is an exception coming from the masterkey decryption already.

Best

Tim

**Comment by powellnorma** [comment]
> but current android versions (like 12) seem to have changed indeed and fail with

I have run into this problem too. It would be nice if there was a way to extract the private key for newer android versions, especially when using the software fallback (no hardware TEE etc).

> Which is an exception coming from the masterkey decryption already.

I found that we can rename the `.masterkey` file to `.masterkey.bak`, and apps using the keystore still seem to work fine (even after a reboot). So I think this file is not needed anymore for decrypting the password.
